FROM tutum/apache-php
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq install \
  php5-mcrypt
RUN php5enmod mcrypt
# config to enable .htaccess
ADD apache-default /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite
