# App Settings
source: ./src/static/templates
destination: ./.tmp/static/
exclude: ['src/sass/*.scss']


# Site settings
title: >
  JHU IdeaLab
description: > # this means to ignore newlines until "baseurl:"
  Manage your portfolio of projects with ease and intelligence.
  Visualize project plans, resource scheduling, and timesheets.
  Become a Project Management superstar.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.ppmroadmap.com" # the base hostname & protocol for your site

permalink: /news/:year/:month/:day/:title/


# Collections
# collections:
#   features:
#     output: true
#   customers:
#     output: true
#     permalink: /customers/:path/


# Default Settings
# defaults:
#   -
#     scope:
#       path: ""
#       type: customers   # <= here you can specify a collection now!
#     values:
#       layout: page
#       class: _lo-customers
#   -
#     scope:
#       path: ""
#       type: posts   # <= here you can specify a collection now!
#     values:
#       layout: post
#       class: _lo-posts

# email: support@ppmroadmap.com
# twitter_username: ppmroadmap
# github_username:  getroadmap

# Build settings
markdown: kramdown
