web:
  build: config/docker/images/apache-php
  hostname: idealab.jhu.edu
  domainname: idealab.jhu.dev
  volumes:
    - /vagrant/jhu-idealab-site-dev/dist/www:/var/www/html
  volumes_from:
    - data
  links:
    - mysql
  environment:
    - VIRTUAL_HOST=idealab.jhu.dev


mysql:
  image: mysql
  ports:
    - 3306
  environment:
    - VIRTUAL_HOST=mysql.idealab.jhu.dev
    - MYSQL_ROOT_PASSWORD=password


data:
  image: phusion/baseimage
  volumes:
    - /var/lib/mysql
    - /var/www/html/content/uploads

# docker run -d -p 80:80 --name webapp -link mysql:mysql php:5.5


# docker run -d -p 80 -e VIRTUAL_HOST=web.idealab.dev --name webapp -link mysql:mysql -v /vagrant/Documents/projects/jhu-idealab-site-dev/src/www:/app tutum/apache-php

# docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy

# docker run -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=password mysql


# http://passingcuriosity.com/2013/dnsmasq-dev-osx/
