production:
  host: mysql.georgetowncied.org
  database: cied_production
  username: cied_production
  password: 'tAt-jeuS-shU-Dac-phe'
dev:
  host: localhost
  database: p0283
  username: mkthngs_clients
  password: 'jd3CuqGTkE2y2W77e.BLLNoVew76p9pz42FoGmmaYwPuZh=kNH'
local:
  host: localhost
  database: idealab
  username: root
  password: 'password'
